### ISSUE TITLE
Switch to gymnasium

### ISSUE THREAD

**Issue by timokau** [timokau/prefq#21]
Now that imitation is compatible with gymnasium (https://github.com/HumanCompatibleAI/imitation/pull/735) and the [asynchronous preference PR has been updates as well](https://github.com/HumanCompatibleAI/imitation/pull/716), there shouldn't be any blocker for us anymore.

Updating to gymnasium should allow us to get rid of the messy [workaround](https://github.com/timokau/prefq/blob/4cf8c177c9449141ec4c64bc7f7817c6c8cbbebb/scripts/run_imitation_example.sh#L6) to install gym (among other benefits).

**Comment by timokau** [comment]
To do this, we need to switch from the `ecda-experiment` branch of rk1a's fork of imitation to the `human-prefs` branch used in [the PR](https://github.com/HumanCompatibleAI/imitation/pull/716) (update `pyproject.toml`), do a `poetry update` and fix the issues that aries due to the breaking changes in gymnasium.

**Comment by patrickab** [comment]
Issue resolved. By specifying the "pyproject.toml" file to avoid PyTorch versions 2.0.1 and 2.1.0 and GPU drivers, CUDA related errors can be avoided. Information has been added as a comment in the corresponding file.

https://stackoverflow.com/questions/76327419/valueerror-libcublas-so-0-9-not-found-in-the-system-path

**Comment by timokau** [comment]
Thanks for digging into the pytorch issue!

**Comment by timokau** [comment]
Done in #27.
