### ISSUE TITLE
Avoid global variables in the server

### ISSUE THREAD

**Issue by timokau** [timokau/prefq#23]
We currently have some global variables in the server implementation. We should avoid this. I am sure Flask offers some better solution to store state.

**Comment by patrickab** [comment]
Global Variables do no longer exist in the current state of work, this Issue can be closed

**Comment by timokau** [comment]
Thanks! Let's close it when the relevant PR is merged / let github close it automatically at that point :)

**Comment by patrickab** [comment]
it looks like the relevant commit got modified during a messy rebase, & is no longer part of the commit history - however, the issue remains solved, only within https://github.com/timokau/prefq/commit/d75cf9d66a25dc883c989aa687d61782ec1f3491 the closing keyword was not mentioned again

**Comment by timokau** [comment]
Thanks for the reminder.
