### ISSUE TITLE
Add support for other video formats

### ISSUE THREAD

**Issue by timokau** [timokau/prefq#24]
We currently assume (and only test the case of) webm videos. We should extend that support and/or check the format and give a useful error message in case of an incompatible one.

**Comment by patrickab** [comment]
Good news: I've just tested several file encodings then .webm (.mp4/.wmv/.mpeg), and they are all compatible. And its more than that: regardless of the video format sent from the Query Client, the server can chose which encoding to use, by simply appending the desired file encoding to the string, and then calling save() from werkzeug.Filestorage.save(). This function can probably perform some kind of conversion process by default. I checked the file encoding by saving the videos from the .html interface, and the file encodings were indeed associated as specified inside the server script.

**Comment by timokau** [comment]
So the client can send in whatever format and the server just saves as webm? Doesn't that use a lot of processing power on the server?

**Comment by timokau** [comment]
Are you sure the server actually converts the video, or is the browser maybe just able to determine the video format despite the wrong extension (i.e., determine that a video is mp4 even though the extension is .webm)?

**Comment by patrickab** [comment]
i just checked it, again, and apparently i was wrong. when attempting to download the file it is first recognized as the file encoding specified by the server, but after storing it on the disk it will be stored as the file format specified by the client. However, both .mp4 and .webm encodings have been proven to be compatible with the server. As a consequence, the file encoding specified within the server script can be deleted. Here's what's happening in detail

Query Client: sends .mp4 encoded file
Server: stores `right_filename = query_id + "-left.mpeg"`
Feedback Client: downloads video from server (from windows detected detected as mpeg)
Feedback Client: video appears stored on the disk as `01-02-left.mp4`

i propose sending other common file encodings to the server, to ensure compatibility, & then listing compatible encodings in the documentation of the server script. additionally, i propose deleting the file extension from the flename string within the server script: `right_filename = query_id + "-left"`

**Comment by timokau** [comment]
I do not quite understand your proposal. How exactly is the file encoding detected? Where does this happen?

**Comment by patrickab** [comment]
regarding this issue we concluded to leave the file extension on the server side for readability. In practice, the server script does not require the file extension, but can extract the filetype from the binary data received from the QueryClient. Maybe adding a short explanatory comment might be a good idea?

```python
@app.route("/videos", methods=["POST"])
def receive_videos():

    [...]

    left_filename = query_id + "-left.webm"
    right_filename = query_id + "-right.webm"

    [...]
```

**Comment by timokau** [comment]
I think we should either (1) use the file extension the client gives us or (2) raise a warning if it is not a webm however. Always assuming webm may cause problems. Option (1) would be best.

**Comment by timokau** [comment]
Isn't that implicitly specified in the filename already?
