### ISSUE TITLE
System Crash due to Cache Issues

### ISSUE THREAD

**Issue by patrickab** [timokau/prefq#32]
The current state of work in https://github.com/timokau/prefq/pull/27 led to overflowing disk (cached data was written to disk) on my WSL System, which ended up blocking disk space permanently and could not be easily freed again. The issue lies in the `mkdtemp()` function (used in [updated_imitation_modules.py](https://github.com/timokau/prefq/blob/main/prefq/examples/updated_imitation_modules.py)), which is a C based library function, that does not offer any built-in mechanism to limit disk space usage and therefore requires the user to ensure in a bulletproof manner, that no memory leaks occur. This is a major disadvantage in terms of maintainability & usability. 

Under all tests using gymnasium 0.28.0 no errors occurred, it has just been now, after updating to gymnasium 0.29.0, that the execution of the [imitation example](https://github.com/timokau/prefq/blob/main/prefq/examples/imitation_preference_comparisons.py) led to a huge memory leak of roughly 70GB. I cannot fully exclude the possibility, that this has been a cumulative memory leak stacking up over several days of testing, however, to me it seems very likely that this is not the case, considering that a minimum of 500 video pairs has been evaluated on my machine, while a batch of 20 video pairs & subsequent training can already consume roughly 6GB of storage.

Also, it is important to mention, that the blocked disk space seemed (this statement is not fully verified, as 5GB of cached data, unrelated to PrefQ) to be available within WSL, and only appeared blocked within the Windows Filesystem. Either way, some type of security barrier must urgently be implemented.

In this light, considerations regarding a more manageable and risk-free solution, seem necessary. The optimal solution would be a cache object, that automatically clears all allocated memory, after either successful or forceful termination (SIGKILL w/ ctrl+c). The Cache Memory used in [updated_imitation_modules.py](https://github.com/timokau/prefq/blob/main/prefq/examples/updated_imitation_modules.py) appears to only be closed, when the `RenderImageInfoWrapper.close()` function is called, which triggers `shutil.rmtree(self.file_cache)`. This function might not be called anymore under the updated Gymnasium/Imitation API, possibly leading to the issue, that we are observing here. 

During a short search, i came across these two promising libraries:

https://pypi.org/project/diskcache/
https://pypi.org/project/cache-to-disk/

**Comment by timokau** [comment]
> The current state of work in #27 led to overflowing disk (cached data was written to disk) on my WSL System, which ended up blocking disk space permanently and could not be easily freed again. The issue lies in the `mkdtemp()` function (used in [updated_imitation_modules.py](https://github.com/timokau/prefq/blob/main/prefq/examples/updated_imitation_modules.py)), which is a C based library function, that does not offer any built-in mechanism to limit disk space usage and therefore requires the user to ensure in a bulletproof manner, that no memory leaks occur. This is a major disadvantage in terms of maintainability & usability.

I don't understand, what do you mean by limit disk space usage? Limit how much data can be stored in a folder?

> Under all tests using gymnasium 0.28.0 no errors occurred, it has just been now, after updating to gymnasium 0.29.0, that the execution of the [imitation example](https://github.com/timokau/prefq/blob/main/prefq/examples/imitation_preference_comparisons.py) led to a huge memory leak of roughly 70GB. I cannot fully exclude the possibility, that this has been a cumulative memory leak stacking up over several days of testing, however, to me it seems very likely that this is not the case, considering that a minimum of 500 video pairs has been evaluated on my machine, while a batch of 20 video pairs & subsequent training can already consume roughly 6GB of storage.

That's weird, I would be surprised if the gymnasium update led to this. Can't exclude it though :)

> Also, it is important to mention, that the blocked disk space seemed (this statement is not fully verified, as 5GB of cached data, unrelated to PrefQ) to be available within WSL, and only appeared blocked within the Windows Filesystem. Either way, some type of security barrier must urgently be implemented.
> 
> In this light, considerations regarding a more manageable and risk-free solution, seem necessary. The optimal solution would be a cache object, that automatically clears all allocated memory, after either successful or forceful termination (SIGKILL w/ ctrl+c). The Cache Memory used in [updated_imitation_modules.py](https://github.com/timokau/prefq/blob/main/prefq/examples/updated_imitation_modules.py) appears to only be closed, when the `RenderImageInfoWrapper.close()` function is called, which triggers `shutil.rmtree(self.file_cache)`. This function might not be called anymore under the updated Gymnasium/Imitation API, possibly leading to the issue, that we are observing here.

I think the current solution *is* a cache object that automatically clears after termination (though I am not sure how reliable that is). As far as I know the files also did not show up on disk anymore right? In that case any other way to store files on disk should have the same problem right?
