### ISSUE TITLE
Milestone: Documentation for External Use

### ISSUE THREAD

**Issue by timokau** [timokau/prefq#38]
Right now prefq is usable for basic training, but documentation is lacking and it would be hard for someone unfamiliar with it to get started. We should add some basic documentation. I think most important would be:

- [x] A getting started tutorial that explains how to get from 0 (no prefq installed) to training an agent on Pendulum (on a local machine, with a single trainer). (#55)
- [x] Basic API documentation, at least of the QueryClient interface. For this we should adopt a standard docstring format and look into options for rendering the documentation. (#47)

**Comment by patrickab** [comment]
as a reminder: I think we could close this milestone too :)
