### ISSUE TITLE
Test and document remote feedback

### ISSUE THREAD

**Issue by timokau** [timokau/prefq#39]
In principle it should be possible to run the server, the query client and the feedback client (web browser) on three separate machines. Only the server should need firewall configuration.

This is likely already possible, but not tested yet. We should test it and write a tutorial on how to get this up and running (after the basic tutorial mentioned in #38).

**Comment by patrickab** [comment]
In practice this is already possible. The tutorial also includes information about how to set up a remote cloud server. I should however conduct one last step of thorough *remote* testing under WSL, as this was the concrete configuration, that led to #56.

**Comment by patrickab** [comment]
I hereby confirm that running a remote feedback client with our imitation example does *not* result in the problem described in #56. This has been tested using both WSL and Linux, confirming, that the example is now safe to be used.

**Comment by timokau** [comment]
Great, thanks for checking!
