### ISSUE TITLE
Milestone: Support multiple labelers

### ISSUE THREAD

**Issue by timokau** [timokau/prefq#40]
We currently assume that only a single feedback client is active at a time. We should support multiple labelers. For this, we need to consider how to assign queries to labelers, how to handle non-responses, etc.

**Comment by patrickab** [comment]
Currently the project is implemented in a way, that expects the queries to be sent and answered in a strict order. To keep things short: when rendering a webinterface, the query is not removed from the queue. Queries are only removed, when the evaluation is complete.

For solving this problem I would suggest (a) popping elements from the queue, when queries are requested from Feedback Clients & (b)  the implementation of a secondary, datastructure (preferably list, details later), for holding queries sent to Feedback Clients. The procedure could look somehow like this:

1. feedback-client-a sends GET request to /
2. Server pops query-1 from the queue
3. Server adds query-id-1 to list
4. Server sends back web interface containing query-1
5. feedback-cient-b sends GET request to /
6. Server pops query-2 from the queue
7. Server adds query-id-2 to list
8. Server sends back web interface containing query-2
9. feedback-client-b sends feedback-2, query-id-2
11. Server removes query-id-2 from list, then stores feedback-2 
12. feedback-client-b sends another GET request to /
13. Server attempts to pop queue, but queue is empty
14. Server selects first query (=the oldest query) from the list instead, then sends web-interface to feedback-client-b
15. feedback-client-b sends feedback-1, query-id-1
16. Server removes query-id-1 from list, then stores feedback-1
17. feedback-client-a sends feedback-1, query-id-1
18. Server attempts removing query-id-1, which doesnt exist. Therefore, the feedback is discarted

The reasoning behind using a list, is that using a list we can simply do `query-list.remove(query-id-i)` to delete the feedback, which can come in a random order. Still, when we perform `query-list.append(query-id-i)` we have an ordered data structure, and we will always have the oldest element at the first position. When the queue is empty, we can then simply select the oldest unevaluated query. By doing so we circumvent the problem of re-populating the queue, which led to the problem described in #35. At the moment - as mentioned above - we solved the problem by considering only the single-user-case, and always render `query-queue[0]`, until we receive feedback for it.
