### ISSUE TITLE
Automatic page reloads only triggered after initial manual reload

### ISSUE THREAD

**Issue by patrickab** [timokau/prefq#46]
This [template](https://github.com/timokau/prefq/blob/main/prefq/templates/no_data_availible.html) is supposed to be triggered every few seconds, until new data is availible. However, this only works after manually reloading the page once. Probably this behavior can be adjusted, by modifying the structure of the underlying .html code accordingly.

**Comment by timokau** [comment]
You closed this, but I think there is no PR for this yet right? I'll reopen for now. Please add a "closes #46" to the PR when you open one. This issue will then automatically be closed when the PR is merged.
