### ISSUE TITLE
Missing videos for Static Query Example

### ISSUE THREAD

**Issue by patrickab** [timokau/prefq#60]
Currently the videos required for `run_static_queries.sh`/`static_queries.py` are missing in this repository. We've also recently removed `random_recordings.py`. For future users we should upload a batch of examplatory videos.

**Comment by patrickab** [comment]
I just checked the folder structure, it turns out that the videos are just located deeper inside the folder structure (`./prefq/examples/videos/lunarlander_random`).

I think it would best to relocate these videos to `./videos`.

**Comment by timokau** [comment]
If we move them, I would prefer a name that makes it clear that the videos are not part of the project itself, e.g., `example-recordings`.
