### ISSUE TITLE
Python Dependency Restriction

### ISSUE THREAD

**Issue by patrickab** [timokau/prefq#76]
Within `pyproject.toml` we have the project restricted to `python = "^3.9"`. This is a slight problem when setting up a new server instance on OCI, as the server images (ubuntu 20.04) come with python 3.8 preinstalled. Changing the restriction to `python = "^3.8"` and running `poetry update` does not seem to hinder the functionality of the project in any way, but makes it executable out of the box for future users. Is there any good reason to stay with Version 3.9? Otherwise, I suggest removing this restriction or setting it to a lower version.

**Comment by timokau** [comment]
No reason to restrict to 3.9 from my side, feel free to relax the restriction.
